"""PostgreSQL database for tracking signals, portfolio snapshots, and trades."""

import json
import logging
from datetime import datetime, timedelta, timezone
from math import isfinite

import psycopg
from psycopg import sql

from constants import DATABASE_URL, SNAPSHOT_GATE_MIN_RATIO, SNAPSHOT_GATE_MAX_AGE_HOURS

logger = logging.getLogger(__name__)


def get_connection() -> psycopg.Connection:
    return psycopg.connect(DATABASE_URL)


def init_db() -> None:
    with get_connection() as conn:
        _create_schema(conn)
        _add_missing_columns(conn)
        _retype_timestamps(conn)
    logger.info("Database initialized")


def _create_schema(conn: psycopg.Connection) -> None:
    conn.execute("""
        CREATE TABLE IF NOT EXISTS signals (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            timestamp TIMESTAMPTZ NOT NULL,
            allocations TEXT NOT NULL,
            total_pct DOUBLE PRECISION NOT NULL,
            message_timestamp TEXT
        );

        CREATE TABLE IF NOT EXISTS snapshots (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            timestamp TIMESTAMPTZ NOT NULL,
            signal_id BIGINT REFERENCES signals(id),
            total_value_usd DOUBLE PRECISION NOT NULL,
            balances TEXT NOT NULL,
            prices TEXT NOT NULL,
            values_usd TEXT NOT NULL,
            targets TEXT NOT NULL,
            partial BOOLEAN NOT NULL DEFAULT FALSE
        );

        CREATE TABLE IF NOT EXISTS trades (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            timestamp TIMESTAMPTZ NOT NULL,
            signal_id BIGINT REFERENCES signals(id),
            symbol TEXT NOT NULL,
            side TEXT NOT NULL,
            amount DOUBLE PRECISION NOT NULL,
            price DOUBLE PRECISION,
            usd_value DOUBLE PRECISION,
            status TEXT NOT NULL,
            order_id TEXT,
            dry_run INTEGER NOT NULL,
            fee_amount DOUBLE PRECISION,
            fee_currency TEXT,
            fee_rate DOUBLE PRECISION
        );
    """)

def _add_missing_columns(conn: psycopg.Connection) -> None:
    """Bring databases created by an earlier version up to the current schema."""
    for table, col, col_type in [
        ("trades", "fee_amount", "DOUBLE PRECISION"),
        ("trades", "fee_currency", "TEXT"),
        ("trades", "fee_rate", "DOUBLE PRECISION"),
        ("signals", "message_timestamp", "TEXT"),
        ("snapshots", "partial", "BOOLEAN NOT NULL DEFAULT FALSE"),
    ]:
        conn.execute(
            sql.SQL("ALTER TABLE {} ADD COLUMN IF NOT EXISTS {} " + col_type).format(
                sql.Identifier(table), sql.Identifier(col)
            )
        )


def _retype_timestamps(conn: psycopg.Connection) -> None:
    """Promote timestamp columns to TIMESTAMPTZ.

    The SQLite migration carried them over as ISO text, leaving every range query
    to compare bytes rather than instants. Naive columns are converted too: mixing
    them with the aware datetimes this module writes raises at runtime.
    """
    for table in ("signals", "snapshots", "trades"):
        legacy = conn.execute(
            """SELECT data_type FROM information_schema.columns
               WHERE table_schema = current_schema() AND table_name = %s
                 AND column_name = 'timestamp'
                 AND data_type IN ('text', 'timestamp without time zone')""",
            (table,),
        ).fetchone()
        if not legacy:
            continue
        logger.info("Converting %s.timestamp from %s to timestamptz", table, legacy[0])
        conn.execute(
            sql.SQL(
                "ALTER TABLE {} ALTER COLUMN timestamp TYPE TIMESTAMPTZ "
                "USING timestamp::TIMESTAMPTZ"
            ).format(sql.Identifier(table))
        )


def record_signal(allocations: dict, message_timestamp: str | None = None) -> int:
    total_pct = sum(allocations.values())
    with get_connection() as conn:
        signal_id = conn.execute(
            """INSERT INTO signals (timestamp, allocations, total_pct, message_timestamp)
               VALUES (%s, %s, %s, %s) RETURNING id""",
            (datetime.now(timezone.utc), json.dumps(allocations), total_pct, message_timestamp),
        ).fetchone()[0]
    logger.info("Recorded signal id=%d with %d assets totaling %.1f%% (msg_time=%s)",
                signal_id, len(allocations), total_pct, message_timestamp)
    return signal_id


def _is_collapse(total_value_usd: float, now: datetime, previous: dict | None) -> bool:
    """True when a total is too far below a recent clean snapshot to be a real drawdown.

    Backstop for the degraded-venue check in Balance.degraded, for failures that
    report a plausible-looking total instead of raising. `previous` must be a clean
    snapshot, or a single bad row would become the benchmark that admits the next
    one. The gate disarms once that baseline ages out, so a genuine collapse cannot
    wedge writes forever; a baseline dated in the future is ignored for the same
    reason, since its age never grows.
    """
    if not isfinite(total_value_usd):
        return True
    if previous is None or previous["total_value_usd"] <= 0:
        return False
    age = now - previous["timestamp"]
    if not timedelta(0) <= age <= timedelta(hours=SNAPSHOT_GATE_MAX_AGE_HOURS):
        return False
    return total_value_usd < previous["total_value_usd"] * SNAPSHOT_GATE_MIN_RATIO


def record_snapshot(signal_id: int | None, total_value_usd: float,
                    balances: dict, prices: dict, values_usd: dict, targets: dict,
                    partial: bool = False) -> None:
    """Persist a portfolio valuation.

    `partial` marks a snapshot taken while a venue was unreadable. Those rows are
    kept for the audit trail but excluded from every baseline query, so an outage
    leaves a gap in /performance rather than a false six-digit percentage.
    """
    now = datetime.now(timezone.utc)
    if not partial and _is_collapse(total_value_usd, now, get_latest_snapshot()):
        logger.error(
            "Recording snapshot of $%.2f USD as partial: implausible drop from the last clean one",
            total_value_usd,
        )
        partial = True

    with get_connection() as conn:
        conn.execute(
            """INSERT INTO snapshots
               (timestamp, signal_id, total_value_usd, balances, prices, values_usd,
                targets, partial)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
            (
                now,
                signal_id,
                total_value_usd,
                json.dumps(balances),
                json.dumps(prices),
                json.dumps(values_usd),
                json.dumps(targets),
                partial,
            ),
        )
    logger.info("Recorded %sportfolio snapshot: $%.2f USD",
                "partial " if partial else "", total_value_usd)


def record_trade(signal_id: int | None, symbol: str, side: str, amount: float,
                 price: float | None, usd_value: float | None, status: str,
                 order_id: str | None, dry_run: bool,
                 fee_amount: float | None = None, fee_currency: str | None = None,
                 fee_rate: float | None = None) -> None:
    with get_connection() as conn:
        conn.execute(
            """INSERT INTO trades
               (timestamp, signal_id, symbol, side, amount, price, usd_value,
                status, order_id, dry_run, fee_amount, fee_currency, fee_rate)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            (
                datetime.now(timezone.utc),
                signal_id,
                symbol,
                side,
                amount,
                price,
                usd_value,
                status,
                order_id,
                1 if dry_run else 0,
                fee_amount,
                fee_currency,
                fee_rate,
            ),
        )


def get_latest_signal_id() -> int | None:
    with get_connection() as conn:
        row = conn.execute("SELECT id FROM signals ORDER BY id DESC LIMIT 1").fetchone()
    return row[0] if row else None


def get_latest_allocations() -> dict | None:
    with get_connection() as conn:
        row = conn.execute("SELECT allocations FROM signals ORDER BY id DESC LIMIT 1").fetchone()
    return json.loads(row[0]) if row else None


def get_recent_trades(limit: int = 5) -> list[dict]:
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT timestamp, symbol, side, amount, usd_value, status, dry_run
               FROM trades ORDER BY id DESC LIMIT %s""",
            (limit,),
        ).fetchall()
    return [
        {
            "timestamp": r[0], "symbol": r[1], "side": r[2], "amount": r[3],
            "usd_value": r[4], "status": r[5], "dry_run": bool(r[6]),
        }
        for r in rows
    ]


def _clean_snapshot(clause: str, params: tuple = ()) -> dict | None:
    """Read one snapshot taken while every venue was readable.

    Partial rows are deliberately unreachable here: they exist for the audit trail,
    and using one as a baseline is exactly the bug this module guards against.
    """
    with get_connection() as conn:
        row = conn.execute(
            "SELECT timestamp, total_value_usd FROM snapshots "
            f"WHERE NOT partial {clause}",
            params,
        ).fetchone()
    return {"timestamp": row[0], "total_value_usd": row[1]} if row else None


def get_latest_snapshot() -> dict | None:
    return _clean_snapshot("ORDER BY timestamp DESC LIMIT 1")


def get_snapshot_at_or_before(target_ts: datetime) -> dict | None:
    return _clean_snapshot("AND timestamp <= %s ORDER BY timestamp DESC LIMIT 1", (target_ts,))


def get_earliest_snapshot() -> dict | None:
    return _clean_snapshot("ORDER BY timestamp ASC LIMIT 1")


def get_latest_message_timestamp() -> str | None:
    """Return the newest signal's posted-at timestamp, ignoring unknown ones.

    A scrape that falls back to the page body cannot read a message timestamp
    and records the signal with NULL. Skipping those rows keeps one such scrape
    from resetting the baseline and making the next poll look like a new signal.
    """
    with get_connection() as conn:
        row = conn.execute(
            "SELECT message_timestamp FROM signals "
            "WHERE message_timestamp IS NOT NULL ORDER BY id DESC LIMIT 1"
        ).fetchone()
    return row[0] if row else None
