"""PostgreSQL database for tracking signals, portfolio snapshots, and trades."""

import json
import logging
from datetime import datetime, timezone

import psycopg

from constants import DATABASE_URL

logger = logging.getLogger(__name__)


def get_connection() -> psycopg.Connection:
    return psycopg.connect(DATABASE_URL)


def init_db() -> None:
    conn = get_connection()
    conn.execute("""
        CREATE TABLE IF NOT EXISTS signals (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            timestamp TEXT NOT NULL,
            allocations TEXT NOT NULL,
            total_pct DOUBLE PRECISION NOT NULL,
            message_timestamp TEXT
        );

        CREATE TABLE IF NOT EXISTS snapshots (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            timestamp TEXT NOT NULL,
            signal_id BIGINT REFERENCES signals(id),
            total_value_usd DOUBLE PRECISION NOT NULL,
            balances TEXT NOT NULL,
            prices TEXT NOT NULL,
            values_usd TEXT NOT NULL,
            targets TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS trades (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            timestamp TEXT NOT NULL,
            signal_id BIGINT REFERENCES signals(id),
            symbol TEXT NOT NULL,
            side TEXT NOT NULL,
            amount DOUBLE PRECISION NOT NULL,
            price DOUBLE PRECISION,
            usd_value DOUBLE PRECISION,
            status TEXT NOT NULL,
            order_id TEXT,
            dry_run INTEGER NOT NULL,
            fee_amount DOUBLE PRECISION,
            fee_currency TEXT,
            fee_rate DOUBLE PRECISION
        );
    """)
    # Migrate existing databases that lack newer columns.
    for table, col, col_type in [
        ("trades", "fee_amount", "DOUBLE PRECISION"),
        ("trades", "fee_currency", "TEXT"),
        ("trades", "fee_rate", "DOUBLE PRECISION"),
        ("signals", "message_timestamp", "TEXT"),
    ]:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {col} {col_type}")
    conn.commit()
    conn.close()
    logger.info("Database initialized")


def record_signal(allocations: dict, message_timestamp: str | None = None) -> int:
    conn = get_connection()
    total_pct = sum(allocations.values())
    cursor = conn.execute(
        """INSERT INTO signals (timestamp, allocations, total_pct, message_timestamp)
           VALUES (%s, %s, %s, %s) RETURNING id""",
        (datetime.now(timezone.utc).isoformat(), json.dumps(allocations), total_pct, message_timestamp),
    )
    signal_id = cursor.fetchone()[0]
    conn.commit()
    conn.close()
    logger.info("Recorded signal id=%d with %d assets totaling %.1f%% (msg_time=%s)",
                signal_id, len(allocations), total_pct, message_timestamp)
    return signal_id


def record_snapshot(signal_id: int | None, total_value_usd: float,
                    balances: dict, prices: dict, values_usd: dict, targets: dict) -> None:
    conn = get_connection()
    conn.execute(
        """INSERT INTO snapshots
           (timestamp, signal_id, total_value_usd, balances, prices, values_usd, targets)
           VALUES (%s, %s, %s, %s, %s, %s, %s)""",
        (
            datetime.now(timezone.utc).isoformat(),
            signal_id,
            total_value_usd,
            json.dumps(balances),
            json.dumps(prices),
            json.dumps(values_usd),
            json.dumps(targets),
        ),
    )
    conn.commit()
    conn.close()
    logger.info("Recorded portfolio snapshot: $%.2f USD", total_value_usd)


def record_trade(signal_id: int | None, symbol: str, side: str, amount: float,
                 price: float | None, usd_value: float | None, status: str,
                 order_id: str | None, dry_run: bool,
                 fee_amount: float | None = None, fee_currency: str | None = None,
                 fee_rate: float | None = None) -> None:
    conn = get_connection()
    conn.execute(
        """INSERT INTO trades
           (timestamp, signal_id, symbol, side, amount, price, usd_value,
            status, order_id, dry_run, fee_amount, fee_currency, fee_rate)
           VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
        (
            datetime.now(timezone.utc).isoformat(),
            signal_id,
            symbol,
            side,
            amount,
            price,
            usd_value,
            status,
            order_id,
            1 if dry_run else 0,
            fee_amount,
            fee_currency,
            fee_rate,
        ),
    )
    conn.commit()
    conn.close()


def get_latest_signal_id() -> int | None:
    conn = get_connection()
    cursor = conn.execute("SELECT id FROM signals ORDER BY id DESC LIMIT 1")
    row = cursor.fetchone()
    conn.close()
    return row[0] if row else None


def get_latest_allocations() -> dict | None:
    conn = get_connection()
    cursor = conn.execute("SELECT allocations FROM signals ORDER BY id DESC LIMIT 1")
    row = cursor.fetchone()
    conn.close()
    return json.loads(row[0]) if row else None


def get_recent_trades(limit: int = 5) -> list[dict]:
    conn = get_connection()
    cursor = conn.execute(
        """SELECT timestamp, symbol, side, amount, usd_value, status, dry_run
           FROM trades ORDER BY id DESC LIMIT %s""",
        (limit,),
    )
    rows = cursor.fetchall()
    conn.close()
    return [
        {
            "timestamp": r[0], "symbol": r[1], "side": r[2], "amount": r[3],
            "usd_value": r[4], "status": r[5], "dry_run": bool(r[6]),
        }
        for r in rows
    ]


def get_snapshot_at_or_before(target_ts: datetime) -> dict | None:
    conn = get_connection()
    cursor = conn.execute(
        """SELECT timestamp, total_value_usd FROM snapshots
           WHERE timestamp <= %s ORDER BY timestamp DESC LIMIT 1""",
        (target_ts.isoformat(),),
    )
    row = cursor.fetchone()
    conn.close()
    return {"timestamp": row[0], "total_value_usd": row[1]} if row else None


def get_earliest_snapshot() -> dict | None:
    conn = get_connection()
    cursor = conn.execute(
        "SELECT timestamp, total_value_usd FROM snapshots ORDER BY timestamp ASC LIMIT 1"
    )
    row = cursor.fetchone()
    conn.close()
    return {"timestamp": row[0], "total_value_usd": row[1]} if row else None


def get_latest_message_timestamp() -> str | None:
    conn = get_connection()
    cursor = conn.execute("SELECT message_timestamp FROM signals ORDER BY id DESC LIMIT 1")
    row = cursor.fetchone()
    conn.close()
    return row[0] if row else None
